Repository YeoGiDa/YeoGiDa-Android, pull requests merged in 2022-12, with the labels that each got.

#30 [UI] 장소 둘러보기 화면
  app/build.gradle
  app/src/main/java/com/starters/yeogida/data/local/PlaceData.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/res/color/color_chip.xml
  app/src/main/res/color/color_radio_button.xml
  app/src/main/res/color/text_color_chip.xml
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_bar.xml
  app/src/main/res/drawable/ic_cafe.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_etc.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_hotel.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_place.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_restaurant.xml
  app/src/main/res/drawable/ic_shopping.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_up.xml
  app/src/main/res/drawable/rectangle_fill_gray100_17.xml
  app/src/main/res/drawable/rectangle_fill_gray200_17.xml
  app/src/main/res/drawable/rectangle_fill_light_yellow_17.xml
  app/src/main/res/drawable/rectangle_fill_pastel_blue_17.xml
  app/src/main/res/drawable/rectangle_fill_pastel_green_17.xml
  app/src/main/res/drawable/rectangle_fill_pastel_orange_17.xml
  app/src/main/res/drawable/rectangle_fill_pastel_purple_17.xml
  app/src/main/res/drawable/rectangle_fill_pastel_red_17.xml
  app/src/main/res/drawable/rectangle_fill_pastel_yellow_17.xml
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/item_place.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 화진, Done, 우선순위 1

#31 [UI] 장소 둘러보기 화면..
  app/src/main/java/com/starters/yeogida/data/local/PlaceData.kt
Labels: 화진, Done, 우선순위 1

#33 [UI] 마이페이지
  app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1

#35 [FEAT] 카카오 로그인 및 회원가입 구현
  .idea/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/DataStoreModule.kt
  app/src/main/java/com/starters/yeogida/YeogidaApplication.kt
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/data/remote/common/TokenData.kt
  app/src/main/java/com/starters/yeogida/data/remote/request/LoginRequestData.kt
  app/src/main/java/com/starters/yeogida/data/remote/request/SignUpRequestData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/CheckMemberResponseData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/SignUpResponseData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/ValidateTokenResponseData.kt
  app/src/main/java/com/starters/yeogida/network/ApiClient.kt
  app/src/main/java/com/starters/yeogida/presentation/common/SingleLiveEvent.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt
  app/src/main/java/com/starters/yeogida/util/CustomEnqueue.kt
  app/src/main/java/com/starters/yeogida/util/FileUtil.kt
  app/src/main/java/com/starters/yeogida/util/UriUtil.kt
  app/src/main/res/drawable-v24/rectangle_border_red_10.xml
  app/src/main/res/drawable/ic_app.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: 영선, Done, 우선순위 1

#37 [FEAT] 마이페이지 로그아웃, 회원탈퇴
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
  app/src/main/res/layout/dialog_custom.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: 영선, Done, 우선순위 1

#41 [NETWORK] 마이페이지 회원탈퇴 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/network/ApiClient.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: 영선, Done, 우선순위 1

#42 [FIX] 스플래시 화면 버전 처리 및 코드 수정
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_app.xml
  app/src/main/res/drawable/img_splash.xml
  app/src/main/res/values/themes.xml
Labels: 영선, Done, 우선순위 1

#43 [UI] 여행지 추가
  .idea/compiler.xml
  .idea/misc.xml
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/com/starters/yeogida/data/local/RegionData.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/BottomSheetFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/RegionAdapter.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/rectangle_fill_main_blue_16.xml
  app/src/main/res/drawable/rectangle_gray100_10.xml
  app/src/main/res/layout/fragment_add_trip.xml
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/item_region.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1

#44 [UI] 알림 화면
  .idea/sonarlint/issuestore/index.pb
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/AlarmFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/navigation/nav_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 2

#45 [FIX] 마이페이지 이름 충돌 해결
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/nav_mypage.xml
Labels: bug, 화진, Done

#46 [FEAT] 카카오 로그인, 회원가입 마무리
  app/.gitignore
  app/src/main/java/com/starters/yeogida/DataStoreModule.kt
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/data/remote/request/SignUpRequestData.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt
  app/src/main/res/layout/activity_join.xml
Labels: 영선, Done, 우선순위 1

#52 [UI] 둘러보기 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/data/local/PlaceBottomSheetData.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/PlaceBottomSheetAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
  app/src/main/res/drawable/ic_star_white.xml
  app/src/main/res/drawable/rectangle_fill_white_20.xml
  app/src/main/res/drawable/rectangle_fill_white_white_8.xml
  app/src/main/res/layout/fragment_around.xml
  app/src/main/res/layout/fragment_place_bottom_sheet.xml
  app/src/main/res/layout/item_bottom_sheet_place.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1

#54 [UI] 여행지 추가 관련 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
  app/src/main/res/drawable/ic_plus_blue.xml
  app/src/main/res/drawable/ic_sad.xml
  app/src/main/res/layout/activity_add_trip.xml
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/nav_add_trip.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1

#55 [UI] 여기 좋아 화면
  app/src/main/java/com/starters/yeogida/data/local/LikeTripData.kt
  app/src/main/java/com/starters/yeogida/network/ApiClient.kt
  app/src/main/java/com/starters/yeogida/presentation/common/RegionCategory.kt
  app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowHomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowLists.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowPagerFragmentStateAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowerFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowingFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/PagerFragmentStateAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/home/TripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikePagerFragmentStateAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripLists.kt
  app/src/main/res/drawable-v24/ic_place_gray.xml
  app/src/main/res/drawable-v24/rectangle_fill_gray100_20.xml
  app/src/main/res/drawable/ic_arrow_downup.xml
  app/src/main/res/drawable/ic_like_selected_red.xml
  app/src/main/res/drawable/selector_btn_like.xml
  app/src/main/res/layout/fragment_follow.xml
  app/src/main/res/layout/fragment_follower.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_like_trip.xml
  app/src/main/res/layout/item_home_trip.xml
  app/src/main/res/layout/item_trip.xml
  app/src/main/res/values/styles.xml
Labels: 영선, Done, 우선순위 1

#56 [UI] 장소 지도로 둘러보기 화면
  app/src/main/java/com/starters/yeogida/data/local/PlaceMapData.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceMapFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/PlaceMapBottomSheetFragment.kt
  app/src/main/res/layout/fragment_around_place_map.xml
  app/src/main/res/layout/fragment_place_map_bottom_sheet.xml
  app/src/main/res/navigation/nav_add_trip.xml
Labels: 화진, Done, 우선순위 1

#58 [UI] 여기 좋아 화면 코드리뷰 반영
  app/src/main/java/com/starters/yeogida/data/local/FollowUserData.kt
  app/src/main/java/com/starters/yeogida/presentation/common/RegionCategory.kt
  app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowHomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowLists.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowPagerFragmentStateAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/User.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikePagerFragmentStateAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_like_trip.xml
  app/src/main/res/layout/item_follow.xml
  app/src/main/res/values/strings.xml
Labels: 영선, Done, 우선순위 1

#60 [FIX] 프로필 이미지 버그
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/util/UriUtil.kt
Labels: 영선, Done, 우선순위 1

#66 [FEAT] 프로필 이미지 null 값이 아닌 빈 값으로 보내기
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/util/ImageUtil.kt
Labels: 영선, Done, 우선순위 1

#67 [FEAT] 지도 권한
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
  app/src/main/res/drawable/ic_app_marker.xml
  app/src/main/res/drawable/ic_marker.xml
Labels: 화진, Done, 우선순위 1

#68 [FEAT] 여행지 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/presentation/common/ImageActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/common/OnItemClick.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/RegionAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/RegionBottomSheetFragment.kt
  app/src/main/res/drawable/ic_x.xml
  app/src/main/res/layout/activity_image.xml
  app/src/main/res/layout/fragment_add_trip.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1

#69 [UI] 장소 상세 화면 디자인
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/data/local/CommentData.kt
  app/src/main/java/com/starters/yeogida/data/local/PlaceDetailData.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailPhotoAdapter.kt
  app/src/main/res/drawable/ic_comment_submit.xml
  app/src/main/res/drawable/ic_star_empty.png
  app/src/main/res/drawable/ic_star_fill.png
  app/src/main/res/drawable/layer_rating_integrate.xml
  app/src/main/res/drawable/oval_mainblue.xml
  app/src/main/res/drawable/rectangle_fill_black_a30_20.xml
  app/src/main/res/drawable/selector_et_blue_comment.xml
  app/src/main/res/drawable/selector_rating_empty.xml
  app/src/main/res/drawable/selector_rating_fill.xml
  app/src/main/res/layout/activity_place.xml
  app/src/main/res/layout/fragment_around.xml
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_place.xml
  app/src/main/res/layout/item_place_detail_photo.xml
  app/src/main/res/layout/item_trip.xml
  app/src/main/res/navigation/nav_place.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 영선, Done, 우선순위 1

#71 [FIX] 이미지 권한 버그
  app/src/main/java/com/starters/yeogida/DataStoreModule.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
Labels: 영선, Done, 우선순위 1

#72 [FEAT] 장소 둘러보기
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceMapFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_around_place_map.xml
  app/src/main/res/navigation/nav_add_trip.xml
  app/src/main/res/navigation/nav_place.xml
Labels: 화진, Done, 우선순위 1

#74 [REFACTOR] navigation icon 적용
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceMapFragment.kt
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_around_place_map.xml
Labels: 화진, Done, 우선순위 1

#77 [NETWORK] 홈 화면 - 최근 게시글 제외
  app/src/main/java/com/starters/yeogida/data/api/HomeService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/BestTravelerResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/MonthlyBestResponse.kt
  app/src/main/java/com/starters/yeogida/network/ApiClient.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/home/BestTravelerAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/TripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt
  app/src/main/java/com/starters/yeogida/util/CustomEnqueue.kt
  app/src/main/res/layout/item_best_traveler.xml
  app/src/main/res/layout/item_home_trip.xml
Labels: 화진, Done, 우선순위 1

#78 [REFACTOR] 변수 이름 변경
  app/src/main/java/com/starters/yeogida/data/local/BestTravelerData.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
Labels: 화진, Done, 우선순위 1

#80 [UI] 여행지 글, 장소 상세 부분 Collapsing Toolbar Layout 관련 디자인 수정
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/values/styles.xml
Labels: 영선, Done, 우선순위 1

#81 [UI] 장소 추가 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceActivity.kt
  app/src/main/res/drawable/ic_star_add_place_empty.png
  app/src/main/res/drawable/ic_star_add_place_fill.png
  app/src/main/res/drawable/layer_rating_integrate_indicator.xml
  app/src/main/res/drawable/layer_rating_integrate_small.xml
  app/src/main/res/layout/activity_add_place.xml
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 영선, Done, 우선순위 1

#83 [NETWORK] 댓글 조회
  app/src/main/java/com/starters/yeogida/DataStoreModule.kt
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/data/local/CommentData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/AscCommentsResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/LoginResponse.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/res/layout/item_comment.xml
Labels: 화진, Done, 우선순위 2

#86 [FEAT] DataStore memberId 값 추가에 따른 코드 추가
  app/src/main/java/com/starters/yeogida/YeogidaApplication.kt
  app/src/main/java/com/starters/yeogida/YeogidaDataStore.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt
Labels: 영선, Done, 우선순위 1

#87 [FEAT] 댓글 조회
  app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
  app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_comment.xml
Labels: 화진, Done, 우선순위 2

#88 [NETWORK] 댓글 추가, 삭제 API
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/remote/request/place/CommentRequest.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/AddCommentResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/PlaceSortBottomSheetFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripSortBottomSheetFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/common/OnItemClick.kt
  app/src/main/java/com/starters/yeogida/presentation/common/SortAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
  app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/RegionAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/RegionBottomSheetFragment.kt
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_comment.xml
Labels: 화진, Done, 우선순위 2

#93 [NETWORK] 장소 둘러보기
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/local/PlaceData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/PlaceListResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/item_place.xml
Labels: 화진, Done, 우선순위 1

#94 [NETWORK] 장소 태그, 정렬
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
Labels: 화진, Done, 우선순위 1

#95 [FEAT] 여행지 - 장소 간 데이터 전달
  app/build.gradle
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/PostTripResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/TripInfoResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
  app/src/main/res/navigation/nav_place.xml
  build.gradle
Labels: 화진, Done, 우선순위 1

#97 [FEAT] 알림 초기 세팅
  app/.gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/YeogidaFirebaseMessagingService.kt
  build.gradle
Labels: 화진, Done, 우선순위 2

#98 [FEAT] 장소 추가 화면 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/presentation/common/ImageBindingAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceImgAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceImageClickListener.kt
  app/src/main/res/drawable/ic_star_add_place_empty.png
  app/src/main/res/drawable/ic_star_add_place_fill.png
  app/src/main/res/drawable/ic_x.xml
  app/src/main/res/drawable/oval_fill_white_border.xml
  app/src/main/res/drawable/rectangle_fill_gray200_border_12.xml
  app/src/main/res/layout/activity_add_place.xml
  app/src/main/res/layout/item_add_place_photo.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle.properties
Labels: 영선, Done, 우선순위 1

#104 [UI] 댓글 단 장소
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyCommentPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_comment_place.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_place.xml
  app/src/main/res/navigation/nav_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 2

#105 [NETWORK] 장소 상세 API 연결
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/local/PlaceDetailData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/AscCommentsResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/PlaceDetailResponse.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/common/Event.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailPhotoAdapter.kt
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_place.xml
Labels: 영선, Done, 우선순위 1

#106 [UI] 나의 여행지
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyTripFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_trip.xml
  app/src/main/res/navigation/nav_mypage.xml
Labels: 화진, Done, 우선순위 1

#109 [FEAT] 클러스터링 초기 세팅
  app/build.gradle
  app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/Place.kt
Labels: 화진, Done, 우선순위 1

#112 [UI] 마이페이지 UI 수정
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_comment_black.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_support.xml
  app/src/main/res/drawable/ic_trip.xml
  app/src/main/res/drawable/ic_withdraw.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1

#116 [FEAT] 지역 데이터 추가
  app/src/main/java/com/starters/yeogida/presentation/trip/RegionBottomSheetFragment.kt
Labels: 화진, Done, 우선순위 1

#114 [NETWORK] 장소 지도로 보기
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/local/PlaceMapData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/PlaceMapListResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceMapFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/PlaceMapBottomSheetFragment.kt
Labels: 화진, Done, 우선순위 2

#118 [NETWORK] 여기 좋아 화면 API 연결
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/data/local/LikeTripData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/LikeTripResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripLists.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyTripFragment.kt
  app/src/main/res/layout/fragment_like_trip.xml
  app/src/main/res/layout/item_trip.xml
Labels: 영선, Done, 우선순위 1

#119 [NETWORK] 장소 추가 API 연결
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/PlaceDetailResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_add_place.xml
  app/src/main/res/navigation/nav_place.xml
Labels: 영선, Done, 우선순위 1

#121 [FIX] 여기 좋아 클릭 버그
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripViewModel.kt
Labels: bug, 영선, Done, 우선순위 1

#122 [FEAT] 장소 지도로 보기
  app/src/main/java/com/starters/yeogida/presentation/around/PlaceMapBottomSheetFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_place_map_bottom_sheet.xml
  app/src/main/res/navigation/nav_place.xml
Labels: 화진, Done, 우선순위 2

#124 [NETWORK] FCM 토큰
  app/src/main/java/com/starters/yeogida/data/remote/request/LoginRequestData.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt
Labels: 화진, Done, 우선순위 2

#133 [UI] 유저 상세 화면 UI
  app/src/main/java/com/starters/yeogida/data/local/FollowUserData.kt
  app/src/main/java/com/starters/yeogida/data/local/UserProfileData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/BestTravelerResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowLists.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/home/BestTravelerAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileViewModel.kt
  app/src/main/res/drawable/ic_report.xml
  app/src/main/res/drawable/rectangle_fill_gray_200_20.xml
  app/src/main/res/drawable/rectangle_fill_main_blue_20.xml
  app/src/main/res/drawable/selector_btn_follow.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/layout/item_best_traveler.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_follow.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/navigation/nav_place.xml
  app/src/main/res/values/strings.xml
Labels: 영선, Done, 우선순위 1

#137 [FEAT] 푸시 알림
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/MainActivity.kt
  app/src/main/java/com/starters/yeogida/YeogidaFirebaseMessagingService.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
Labels: 화진, Done, 우선순위 2

#138 [BUG] 장소 둘러보기 필터
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
Labels: bug, 화진, Done, 우선순위 1

#139 [NETWORK] 팔로잉/팔로우 화면 API 연결
  app/src/main/java/com/starters/yeogida/data/api/FollowService.kt
  app/src/main/java/com/starters/yeogida/data/local/FollowUserData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/follow/FollowUserResponse.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowLists.kt
  app/src/main/res/layout/fragment_follow.xml
  app/src/main/res/layout/item_follow.xml
Labels: 영선, Done, 우선순위 1

#140 [NETWORK] 알림 화면
  app/src/main/java/com/starters/yeogida/data/api/MyPageService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/mypage/NotificationListResponse.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/AlarmFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/NotificationAdapter.kt
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/item_alarm.xml
Labels: 화진, Done, 우선순위 2

#141 [NETWORK] 유저 상세 API
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/MainActivity.kt
  app/src/main/java/com/starters/yeogida/data/api/FollowService.kt
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/data/local/UserProfileData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/userProfile/UserProfileResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/navigation/nav_place.xml
  app/src/main/res/navigation/nav_user_profile.xml
Labels: 영선, Done, 우선순위 1

#142 [UI] 여행지 상세 좋아요 누른 유저 목록
  app/src/main/java/com/starters/yeogida/data/local/TripLikeUserData.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserListAdapter.kt
  app/src/main/res/layout/fragment_trip_like_user.xml
  app/src/main/res/layout/item_trip_like_user.xml
  app/src/main/res/navigation/nav_place.xml
  app/src/main/res/values/strings.xml
Labels: 영선, Done, 우선순위 2

#143 [UI] 여행지 상세 부분 작성자 정보 추가
  app/build.gradle
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/TripInfoResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserFragment.kt
  app/src/main/res/drawable/rectangle_fill_black_a30_16.xml
  app/src/main/res/drawable/rectangle_fill_black_transparent_top_20.xml
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_trip_like_user.xml
  app/src/main/res/layout/item_place_detail_photo.xml
  app/src/main/res/navigation/nav_place.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 영선, Done, 우선순위 1

#145 [FEAT] 알림 목록
  app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/AlarmFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/NotificationAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/item_alarm.xml
Labels: 화진, Done, 우선순위 2

#151 [NETWORK] 여행지 상세 API 연결
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/data/local/TripLikeUserData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/BestTravelerResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/TripInfoResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/TripLikeUserResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserListAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/home/BestTravelerAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_trip_like_user.xml
  app/src/main/res/navigation/nav_place.xml
Labels: 영선, Done, 우선순위 1

#153 [FIX] 여기 좋아 버그 - 태그
  app/google-services.json
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/fragment_place_map_bottom_sheet.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_place.xml
Labels: 화진, Done, 우선순위 1

#154 [NETWORK] 둘러보기 화면
  app/src/main/java/com/starters/yeogida/data/api/AroundService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/ClusterPlaceResponse.kt
  app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
Labels: 화진, Done, 우선순위 1

#155 [NETWORK] 장소 둘러보기 마커
  app/src/main/java/com/starters/yeogida/data/api/AroundService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/ClusterMarkerResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/Place.kt
  app/src/main/java/com/starters/yeogida/presentation/around/PlaceBottomSheetAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
  app/src/main/res/layout/fragment_place_bottom_sheet.xml
  app/src/main/res/layout/item_bottom_sheet_place.xml
Labels: 화진, Done, 우선순위 1

#157 [NETWORK] 여기 좋아 탭 버튼 동적 추가 및 검색 API 연결
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/data/local/LikeTripData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/trip/LikeTripResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripLists.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripObj.kt
  app/src/main/res/drawable/ic_like_trip_empty.png
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_like_trip.xml
  app/src/main/res/values/strings.xml
Labels: 영선, Done, 우선순위 1

#158 [FEAT] 알림 설정
  app/src/main/java/com/starters/yeogida/MainActivity.kt
  app/src/main/java/com/starters/yeogida/YeogidaDataStore.kt
  app/src/main/java/com/starters/yeogida/YeogidaFirebaseMessagingService.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/NotificationSettingFragment.kt
  app/src/main/res/layout/fragment_notification_setting.xml
Labels: 화진, Done, 우선순위 2

#160 [FEAT] 지도 마커 커스텀
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceMapFragment.kt
  app/src/main/res/drawable/ic_marker.xml
Labels: 화진, Done, 우선순위 3

#163 [NETWORK] 팔로잉의 최근 게시글
  app/src/main/java/com/starters/yeogida/data/api/HomeService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/HomeTripResponseResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
Labels: 화진, Done, 우선순위 1

#165 [FEAT] 홈 화면 로직
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/TripAdapter.kt
Labels: 화진, Done, 우선순위 1

#168 [UI] 여행지, 장소 삭제
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/MoreBottomSheetFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_place_detail.xml
Labels: 화진, Done, 우선순위 1

#170 [UI] 여기 좋아, 유저 상세 맨 위로 버튼 만들기
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/TripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileViewModel.kt
  app/src/main/res/layout/fragment_like_trip.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/values/strings.xml
Labels: 영선, Done, 우선순위 3

#172 [NETWORK] 여행지 삭제, 장소 삭제
  app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
Labels: 화진, Done, 우선순위 1

#174 [FEAT] 플로팅 버튼, 더보기 버튼
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_around_place.xml
  app/src/main/res/layout/fragment_place_detail.xml
Labels: 화진, Done, 우선순위 1

#176 [UI] 신고 UI
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/MoreBottomSheetFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
  app/src/main/res/layout/fragment_user_profile.xml
Labels: 화진, Done, 우선순위 3

#178 [FEAT] 신고
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_around_place.xml
Labels: 화진, Done, 우선순위 3

#180 [NETWORK] 신고
  app/src/main/java/com/starters/yeogida/data/api/UserService.kt
  app/src/main/java/com/starters/yeogida/data/remote/request/ReportRequest.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
Labels: 화진, Done, 우선순위 3

#181 [FEAT] 장소 추가 시 장소 마커 찍기
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceFragment.kt
  app/src/main/res/layout/fragment_add_place.xml
Labels: 화진, Done, 우선순위 3

#182 [NETWORK] 마이페이지 API 연결
  app/src/main/java/com/starters/yeogida/data/api/MyPageService.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/common/PlaceData.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/mypage/MyPlaceResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/mypage/MyProfileResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/mypage/MyTripResponse.kt
  app/src/main/java/com/starters/yeogida/data/remote/response/place/PlaceListResponse.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/ChangeProfileFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyCommentPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyTripAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/mypage/MyTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_change_profile.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_like_trip.xml
  app/src/main/res/layout/fragment_my_comment_place.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_trip.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/layout/item_my_trip.xml
  app/src/main/res/layout/item_place.xml
  app/src/main/res/navigation/nav_mypage.xml
  app/src/main/res/values/strings.xml
Labels: 영선, Done, 우선순위 1

#186 [FIX] 데모 관련 버그 수정
  app/src/main/java/com/starters/yeogida/data/api/TripService.kt
  app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceFragment.kt
  app/src/main/res/layout/fragment_my_comment_place.xml
  app/src/main/res/layout/fragment_my_trip.xml
Labels: bug, 영선, Done, 우선순위 1

#191 [FEAT] 앱 아이콘, 앱 이름
  app/src/debug/ic_app_icon-playstore.png
  app/src/debug/res/drawable/ic_app_icon_background.xml
  app/src/debug/res/drawable/ic_app_icon_foreground.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_app_icon.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_app_icon_round.xml
  app/src/debug/res/mipmap-hdpi/ic_app_icon.png
  app/src/debug/res/mipmap-hdpi/ic_app_icon_round.png
  app/src/debug/res/mipmap-mdpi/ic_app_icon.png
  app/src/debug/res/mipmap-mdpi/ic_app_icon_round.png
  app/src/debug/res/mipmap-xhdpi/ic_app_icon.png
  app/src/debug/res/mipmap-xhdpi/ic_app_icon_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_icon.png
  app/src/debug/res/mipmap-xxhdpi/ic_app_icon_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_icon.png
  app/src/debug/res/mipmap-xxxhdpi/ic_app_icon_round.png
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_app_icon.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1
