Repository YeoGiDa/YeoGiDa-Android, pull requests merged in 2022-11, with the labels that each got.

#2 [FEAT] 프로젝트 기초세팅
  .gitignore
  README.md
  app/build.gradle
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 화진, Done

#7 [UI] 로그인 화면 레이아웃 추가
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/LoginActivity.kt
  app/src/main/res/drawable-v24/img_google.png
  app/src/main/res/drawable-v24/img_kakao.PNG
  app/src/main/res/drawable-v24/img_naver.png
  app/src/main/res/drawable-v24/rectangle_naver_green_radius_12.xml
  app/src/main/res/drawable-v24/rectangle_white_radius_12.xml
  app/src/main/res/drawable/rectangle_kakao_yellow_radius_12.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 영선, Done, 우선순위 1

#14 [UI] 회원가입 화면 디자인 완료
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/ui/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/ui/user/LoginActivity.kt
  app/src/main/res/drawable-v24/rectangle_border_red_10.xml
  app/src/main/res/drawable-v24/rectangle_fill_naver_green_12.xml
  app/src/main/res/drawable-v24/rectangle_fill_white_12.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_plus_image.xml
  app/src/main/res/drawable/main_blue_cursor.xml
  app/src/main/res/drawable/oval_gray100.xml
  app/src/main/res/drawable/oval_white.xml
  app/src/main/res/drawable/rectangle_border_main_blue_10.xml
  app/src/main/res/drawable/rectangle_fill_gray100_10.xml
  app/src/main/res/drawable/rectangle_fill_kakao_yellow_12.xml
  app/src/main/res/drawable/rectangle_fill_light_blue_10.xml
  app/src/main/res/drawable/rectangle_fill_main_blue_10.xml
  app/src/main/res/drawable/selector_btn_blue.xml
  app/src/main/res/drawable/selector_et_blue.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 영선, Done, 우선순위 1

#26 [UI] 스플래시 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/like/LikeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
  app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt
  app/src/main/res/drawable/ic_app.xml
  app/src/main/res/drawable/img_text_logo.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_around.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-v31/themes.xml
Labels: 영선, Done, 우선순위 1

#28 [FEAT] Util 추가
  app/src/main/java/com/starters/yeogida/data/remote/response/BaseResponse.kt
  app/src/main/java/com/starters/yeogida/util/ContextExt.kt
  app/src/main/java/com/starters/yeogida/util/CustomEnqueue.kt
  app/src/main/java/com/starters/yeogida/util/ResourceExt.kt
Labels: 화진, Done

#29 [UI] 홈
  app/build.gradle
  app/src/main/java/com/starters/yeogida/data/local/BestTravelerData.kt
  app/src/main/java/com/starters/yeogida/data/local/TripData.kt
  app/src/main/java/com/starters/yeogida/presentation/home/BestTravelerAdapter.kt
  app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
  app/src/main/java/com/starters/yeogida/presentation/home/TripAdapter.kt
  app/src/main/res/drawable/ic_like_yellow.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/rectangle_border_gray200_12.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_best_traveler.xml
  app/src/main/res/layout/item_trip.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 화진, Done, 우선순위 1
